name: "Release dev container features"
on:
  workflow_dispatch:
  push:
    branches:
      - devcontainer-feature

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/devcontainer-feature' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: "Publish"
        uses: devcontainers/action@v1
        with:
          publish-features: "true"
          base-path-to-features: "./src"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
